minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true
verifyDepsBeforeRun: false

allowBuilds:
  esbuild: set this to true or false
  vue-demi: set this to true or false

onlyBuiltDependencies:
  - esbuild
  - vue-demi
